name: prova_pratica
description: A simple Dart project to make HTTP requests and handle JSON data.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  pedantic: ^1.11.0
  lints: ^4.0.0
  test: ^1.24.0
